---
# ----------------------------------------------------------------------
# Generate the certificates with "certificates.sh" script in "ca" folder
# ----------------------------------------------------------------------

- hosts: workers
  tasks:
    - name: Copy certs and kubeconfigs
      copy:
        src: ca/{{item}}
        dest: /home/terraform/{{item}}
      with_items:
        - ca.pem
        - worker-{{index}}-key.pem
        - worker-{{index}}.pem
        - worker-{{index}}.kubeconfig
        - kube-proxy.kubeconfig
    - name: Set hostname
      become: true
      hostname:
        name: worker-{{index}}
    - name: Add hostname to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: 10.240.0.2{{index}} worker-{{index}}
    - name: Enable routing
      become: true
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: true
        reload: true

- hosts: controllers
  tasks:
    - name: Copy certs and kubeconfigs
      copy:
        src: ca/{{item}}
        dest: /home/terraform/{{item}}
      with_items:
        - ca.pem
        - ca-key.pem
        - service-account.pem
        - service-account-key.pem
        - kubernetes.pem
        - kubernetes-key.pem
        - admin.kubeconfig
        - kube-controller-manager.kubeconfig
        - kube-scheduler.kubeconfig
        - encryption-config.yaml
    - name: Set hostname
      become: true
      hostname:
        name: controller-{{index}}
    - name: Add hostname to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: 10.240.0.1{{index}} controller-{{index}}
