---

- hosts: lb
  tasks:
    - name: Install haproxy
      become: true
      package:
        name: haproxy
        state: present
    - name: Copy haproxy config
      become: true
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
    - name: Restart haproxy
      become: true
      systemd:
        name: haproxy
        state: restarted
        enabled: true
